module nexus_scheduler::schedule;

//! Interface for [`nexus_scheduler::schedule`].
//!
//! Calls resolve to the published package.

/// Origin of one scheduled [`Occurrence`].
public enum OccurrenceSource has copy, drop, store {
    /// An occurrence scheduled directly, independent of any recurrence.
    Standalone,
    /// An occurrence generated by a recurrence with its iteration index.
    Recurring {
        iteration: u64,
    },
}

/// One bounded unit of scheduled work.
public struct Occurrence has copy, drop, store {
    id: u64,
    start_time_ms: u64,
    deadline_ms: std::option::Option<u64>,
    priority_fee_percentage: u64,
    source: OccurrenceSource,
}

/// Reason an [`Occurrence`] left its [`Schedule`] without dispatch.
public enum OccurrenceWithdrawalReason has copy, drop, store {
    /// A new recurrence replaced the recurrence candidate.
    RecurrenceReplaced,
    /// The controller cleared the recurrence.
    RecurrenceCleared,
    /// The controller canceled the [`Task`].
    TaskCanceled,
    /// Current runtime rejected the immutable proposal contract.
    TaskRejected,
}

/// One lazily materialized recurring candidate.
public struct Recurrence has copy, drop, store {
    next: Occurrence,
    interval_ms: u64,
    remaining: std::option::Option<u64>,
    iteration: u64,
}

/// Bounded ordering state for a [`Task`].
public struct Schedule has store {
    pending: vector<Occurrence>,
    recurrence: std::option::Option<Recurrence>,
    advertised_occurrence_id: std::option::Option<u64>,
    next_occurrence_id: u64,
    dispatched_count: u64,
    last_dispatch_ms: std::option::Option<u64>,
}

/// One occurrence removed from a [`Schedule`] without dispatch.
public struct WithdrawnOccurrence has copy, drop {
    occurrence: Occurrence,
    reason: OccurrenceWithdrawalReason,
}

/// Complete identity changes produced by one schedule mutation.
public struct ScheduleDelta has drop {
    scheduled: vector<Occurrence>,
    withdrawn: vector<WithdrawnOccurrence>,
}

/// Returns the currently advertised occurrence.
public native fun advertised_occurrence(self: &Schedule): std::option::Option<Occurrence>;

/// Returns whether no future occurrence exists.
public native fun is_idle(self: &Schedule): bool;

/// Returns whether the skill dispatch quota is exhausted.
public native fun is_exhausted(
    self: &Schedule,
    policy: nexus_interface::agent::SkillSchedulePolicy,
): bool;

/// Returns the number of pending standalone occurrences.
public native fun pending_count(self: &Schedule): u64;

/// Returns the number of dispatched occurrences.
public native fun dispatched_count(self: &Schedule): u64;

/// Returns the next occurrence identity that will be allocated.
public native fun next_occurrence_id(self: &Schedule): u64;

/// Returns the occurrence identity.
public native fun occurrence_id(self: Occurrence): u64;

/// Returns the requested start timestamp.
public native fun occurrence_start_time_ms(self: Occurrence): u64;

/// Returns the optional absolute deadline.
public native fun occurrence_deadline_ms(self: Occurrence): std::option::Option<u64>;

/// Returns the priority fee percentage.
public native fun occurrence_priority_fee_percentage(self: Occurrence): u64;

/// Returns the occurrence source.
public native fun occurrence_source(self: Occurrence): OccurrenceSource;

/// Returns whether an occurrence is independent of a recurrence.
public native fun occurrence_source_is_standalone(source: OccurrenceSource): bool;
