[package]
name = "nexus_scheduler"
version = "2.0.0-rc.final"
edition = "2024"

[dependencies]
nexus_kernel = { local = "../kernel" }
nexus_primitives = { local = "../primitives" }
nexus_interface = { local = "../interface" }
nexus_tool = { local = "../tool" }
nexus_registry = { local = "../registry" }
nexus_workflow = { local = "../workflow" }

[addresses]
nexus_scheduler = "0x0"
