[package]
name = "nexus_tool"
version = "2.0.0-rc.final"
edition = "2024"

[dependencies]
nexus_primitives = { local = "../primitives" }
nexus_interface = { local = "../interface" }
Talus = { git = "https://github.com/Talus-Network/talus-token.git", subdir = "talus", rev = "2cabe07db8f7fca1884082d50522559eb7abf2fc"}

[addresses]
nexus_tool = "0x0"
